### PR TITLE
Add tokens for writing and reading reports

### PR DESCRIPTION
**Pull request by paulrouget**
2 different secret tokens used to request and push reports.

The request token (`read_secret`) is used through a basic auth mechanism. Any user will do. Only the password is checked.

The push token (`write_secret`) needs to be attached the JSON report (which is then deleted).

### CODE REVIEW

**Comment by paulrouget** [comment]
@jdm r?

**Comment by paulrouget** [comment]
How would we share the read_secret with the servo members?

**Comment by jdm** [comment]
Over private message of some kind.

**Comment by jdm** [comment]
The changes look sensible!

**Pull request merged**
